config/routes.rb
Dvra::Application.routes.draw do  
  scope ':session_secret' do
    # account functions
    resources :users
    get 'users/:id/change_password' => 'users#change_password', :as => 'change_password'
    get 'register' => 'users#new', :as => 'register'

    # products functions
    get 'categories/:category_id(/order/:order(/page/:page))' => 'products#index', :as => 'products'
    get 'products/search(/order/:order(/page/:page))' => 'products#search', :as => 'product_search'
    get 'products/:id' => 'products#show', :as => 'product'
    post 'products/:product_id/reviews' => 'reviews#create', :as => 'product_reviews'

    # cart functions
    get 'cart' => 'cart#show', :as => 'cart'
    post 'cart/add' => 'cart#add', :as => 'add_to_cart'
    post 'cart/remove' => 'cart#remove', :as => 'remove_from_cart'
    put 'cart/update/:product_id' => 'cart#update', :as => 'update_cart_item'
  
    # mailing list functions
    post 'mailing-list' => 'mailing_list#join', :as => 'join_mailing_list'
  
    # login/logout functions
    get 'login' => 'sessions#new', :as => 'login'
    post 'login' => 'sessions#create', :as => 'login'
    delete 'logout' => 'sessions#destroy', :as => 'logout'
  
    # database stuff
    post 'change_level' => 'sessions#change_level', :as => 'change_level'
    delete 'reset' => 'sessions#reset_database', :as => 'reset_database'
  
    # static paths
    match 'statics' => 'statics#show', :as => 'statics'
  
    root :to => 'store#index', :as => 'store'
  end
  
  root :to => 'store#index', :as => 'store'
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  skip_before_filter :protect_from_forgery
  before_filter :get_product, :except => [:show]
  before_filter :make_cart
  
  def show
    p session[:cart]
  end
  
  def add
    item = session[:cart][:items][@product.id]
    session[:cart][:items][@product.id] = item.nil? ? 1 : item+1
    
    redirect_to product_path(session[:session_secret], @product), :notice => "#{@product.name} was added to your cart"
  end
  
  def remove
    session[:cart][:items].delete(@product.id)
    redirect_to cart_path, :notice => "#{@product.name} was removed from your cart"
  end
  
  def update
    qty = (params[:qty] ||= 0).to_i
    
    return remove if qty == 0
    session[:cart][:items][@product.id] = qty if session[:cart][:items][@product.id]

    redirect_to cart_path, :notice => "#{@product.name} was updated in your cart"
  end
  
  private
  def get_product
    @product = Product.find_by_id_and_session_id!(params[:product_id], session[:session_id])
  end
  
  def make_cart
    session[:cart] ||= {:user_id => current_user, :items => {}}
  end
end

app/views/cart/show.html.erb
<h1>My Cart</h1>

<div style="text-align: right;">
  * setting an item's qty = 0 will remove it from your cart
</div>

<table cellpadding="5" cellspacing="0" border="0" width="100%">
  <tr>
    <th width="50">qty</th>
    <th>product</th>
    <th width="70">price</th>
    <th width="70">total</th>
  </tr>
  
  <% running_sum = 0 %>
  <% unless session[:cart][:items].empty? %>
    <% session[:cart][:items].each_pair do |product_id, qty| %>
    <% product = Product.find(product_id) %>
    <% running_sum += product.price*qty %>
      <tr>
        <td align="center">
          <%= form_tag update_cart_item_path(session[:session_secret], product), :method => :put do %>
            <%= text_field_tag :qty, qty, :style => 'width: 20px; text-align: center;', :onblur => 'javascript:$(this).parent().submit();' %>
          <% end %>
        </td>
        <td>
          <strong><%= product.name %></strong>
          <p><%= truncate(product.description, :length => 90) %></p>
        </td>
        <td align="right"><%= number_to_currency(product.price, :precision => 2) %></td>
        <td align="right"><%= number_to_currency(product.price*qty, :precision => 2) %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="4" align="center">You have no items in your cart.<br /><br /><%= link_to 'click here', store_path %> to return to the storefront</td>
    </tr>
  <% end %>
  
  <tr>
    <td colspan="3" align="right"><strong>Total:</strong></td>
    <td align="right"><%= number_to_currency(running_sum, :precision => 2) %></td>
  </tr>
</table>