config/routes.rb
Dvra::Application.routes.draw do  
  scope ':session_secret' do
    # account functions
    resources :users
    get 'users/:id/change_password' => 'users#change_password', :as => 'change_password'
    get 'register' => 'users#new', :as => 'register'

    # products functions
    get 'categories/:category_id(/order/:order(/page/:page))' => 'products#index', :as => 'products'
    get 'products/search(/order/:order(/page/:page))' => 'products#search', :as => 'product_search'
    get 'products/:id' => 'products#show', :as => 'product'
    post 'products/:product_id/reviews' => 'reviews#create', :as => 'product_reviews'

    # cart functions
    get 'cart' => 'cart#show', :as => 'cart'
    post 'cart/add' => 'cart#add', :as => 'add_to_cart'
    post 'cart/remove' => 'cart#remove', :as => 'remove_from_cart'
    put 'cart/update/:product_id' => 'cart#update', :as => 'update_cart_item'
  
    # mailing list functions
    post 'mailing-list' => 'mailing_list#join', :as => 'join_mailing_list'
  
    # login/logout functions
    get 'login' => 'sessions#new', :as => 'login'
    post 'login' => 'sessions#create', :as => 'login'
    delete 'logout' => 'sessions#destroy', :as => 'logout'
  
    # database stuff
    post 'change_level' => 'sessions#change_level', :as => 'change_level'
    delete 'reset' => 'sessions#reset_database', :as => 'reset_database'
  
    # static paths
    match 'statics' => 'statics#show', :as => 'statics'
  
    root :to => 'store#index', :as => 'store'
  end
  
  root :to => 'store#index', :as => 'store'
end

app/models/product.rb
class Product < ActiveRecord::Base
  # relationships
  has_and_belongs_to_many :categories
  has_many :reviews

  # validations
  validates :session_id, :upc, :price, :name, :description, :presence => true
  validates :upc, :uniqueness => { :scope => :session_id }

  # scopes
  scope :active, where(:is_active => true)
  
  # attr
  attr_protected :session_id
  
  # class methods
  class << self
    def search(session_id, query)
      query = "%#{query}%"
      self.where(['products.session_id = ? AND products.name LIKE ? OR products.description LIKE ?', session_id, query, query])
    end
  end
  
  # instance methods
  def to_param
    "#{id}-#{self.name.parameterize}"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @category = Category.find_by_id_and_session_id!(params[:category_id], session[:session_id])
    @products = @category.products.order(params[:order] ||= :name).paginate(:page => params[:page], :per_page => 15)
  end
  
  def show
    @product = Product.find_by_id_and_session_id!(params[:id], session[:session_id])
  end
  
  def edit
    @product = Product.find_by_id_and_session_id!(params[:id], session[:session_id])
  end
  
  def update
    @product = Product.find_by_id_and_session_id!(params[:id], session[:session_id])

    if @product.update_attributes(params[:product])
      redirect_to product_path(session[:session_secret], @product), :notice => 'Updated'
    else
      redirect_to edit_product_path(session[:session_secret], @product), :alert => @product.errors.full_messages
    end
  end
  
  def search
    @q = filter_search(params[:q])
    @products = Product.search(session[:session_id], @q).order(params[:order] ||= :name).paginate(:page => params[:page], :per_page => 15)
  end
end

app/views/admin/products/_category.html.erb
<li>
  <label>
    <%= check_box_tag 'product[category_ids][]', category.id, product.categories.include?(category) %>
    <%= category.name %>
  </label>

  <ul>
    <% category.children.each do |sub_category| %>
      <%= render :partial => 'admin/products/category', :locals => { :product => product, :category => sub_category } %>
    <% end %>
  </ul>
</li>

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product], :html => { :multipart => true } do |f| %>
  <div class="field">
    <%= f.label :upc %><br />
    <%= f.text_field :upc %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  
  <div class="field">
    <%= image_tag @product.image.url(:thumb) unless @product.image.nil? %>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  
  <div class="field">
    <ul>
      <% Category.roots.each do |category| %>
        <%= render :partial => 'admin/products/category', :locals => { :product => @product, :category => category } %>
      <% end %>
    </ul>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/admin/products/index.html.erb
<h1>Products</h1>

<%= link_to 'add product', new_admin_product_path %>

<table cellpadding="5" cellspacing="0" border="0" width="100%">
  <tr>
    <th width="10px">&nbsp;</th>
    <th width="175px"><%= link_to 'upc', admin_products_path(:order => :upc) %></th>
    <th><%= link_to 'title', admin_products_path(:order => :title) %></th>
    <th width="100px"><%= link_to 'price', admin_products_path(:order => :price) %></th>
  </tr>
  
  <% @products.each do |product| %>
  <tr href="<%= edit_admin_product_path(product) %>">
    <td align="center"><%= link_to 'x', admin_product_path(product), :method => :delete %></td>
    <td><%= product.upc %></td>
    <td><%= product.title %></td>
    <td align="right"><%= number_to_currency(product.price) %></td>
  </tr>
  <% end %>
</table>

<%= will_paginate @products %>

<%= link_to 'add product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>