config/routes.rb
Dvra::Application.routes.draw do  
  scope ':session_secret' do
    # account functions
    resources :users
    get 'users/:id/change_password' => 'users#change_password', :as => 'change_password'
    get 'register' => 'users#new', :as => 'register'

    # products functions
    get 'categories/:category_id(/order/:order(/page/:page))' => 'products#index', :as => 'products'
    get 'products/search(/order/:order(/page/:page))' => 'products#search', :as => 'product_search'
    get 'products/:id' => 'products#show', :as => 'product'
    post 'products/:product_id/reviews' => 'reviews#create', :as => 'product_reviews'

    # cart functions
    get 'cart' => 'cart#show', :as => 'cart'
    post 'cart/add' => 'cart#add', :as => 'add_to_cart'
    post 'cart/remove' => 'cart#remove', :as => 'remove_from_cart'
    put 'cart/update/:product_id' => 'cart#update', :as => 'update_cart_item'
  
    # mailing list functions
    post 'mailing-list' => 'mailing_list#join', :as => 'join_mailing_list'
  
    # login/logout functions
    get 'login' => 'sessions#new', :as => 'login'
    post 'login' => 'sessions#create', :as => 'login'
    delete 'logout' => 'sessions#destroy', :as => 'logout'
  
    # database stuff
    post 'change_level' => 'sessions#change_level', :as => 'change_level'
    delete 'reset' => 'sessions#reset_database', :as => 'reset_database'
  
    # static paths
    match 'statics' => 'statics#show', :as => 'statics'
  
    root :to => 'store#index', :as => 'store'
  end
  
  root :to => 'store#index', :as => 'store'
end

app/models/product.rb
class Product < ActiveRecord::Base
  # relationships
  has_and_belongs_to_many :categories
  has_many :reviews

  # validations
  validates :session_id, :upc, :price, :name, :description, :presence => true
  validates :upc, :uniqueness => { :scope => :session_id }

  # scopes
  scope :active, where(:is_active => true)
  
  # attr
  attr_protected :session_id
  
  # class methods
  class << self
    def search(session_id, query)
      query = "%#{query}%"
      self.where(['products.session_id = ? AND products.name LIKE ? OR products.description LIKE ?', session_id, query, query])
    end
  end
  
  # instance methods
  def to_param
    "#{id}-#{self.name.parameterize}"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @category = Category.find_by_id_and_session_id!(params[:category_id], session[:session_id])
    @products = @category.products.order(params[:order] ||= :name).paginate(:page => params[:page], :per_page => 15)
  end
  
  def show
    @product = Product.find_by_id_and_session_id!(params[:id], session[:session_id])
  end
  
  def edit
    @product = Product.find_by_id_and_session_id!(params[:id], session[:session_id])
  end
  
  def update
    @product = Product.find_by_id_and_session_id!(params[:id], session[:session_id])

    if @product.update_attributes(params[:product])
      redirect_to product_path(session[:session_secret], @product), :notice => 'Updated'
    else
      redirect_to edit_product_path(session[:session_secret], @product), :alert => @product.errors.full_messages
    end
  end
  
  def search
    @q = filter_search(params[:q])
    @products = Product.search(session[:session_id], @q).order(params[:order] ||= :name).paginate(:page => params[:page], :per_page => 15)
  end
end

app/views/products/edit.html.erb
<% form_for @product, :html => { :multipart => true } do |f| %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/products/index.html.erb
<h1><%= @category.name %></h1>


<div style="text-align:right;">
  order by: <% %w(name upc price).each do |sort| %>
    <%= link_to sort, {:session_secret => session[:session_secret], :action => 'index', :order => sort, :page => params[:page] || 1} %>
  <% end %>
</div>

<% num_cols = 5 %>
<table cellpadding="10" cellspacing="0" border="0" width="100%">
  <tr>
    <% @products.each_with_index do |product, index| %>
    <% if index%num_cols == 0 %>
    </tr><tr>
    <% end %>
      <td align="center" width="<%= 100.0/num_cols %>%">
        <h3><%= link_to product.name, product_path(session[:session_secret], product) %></h3>
        <div class="photo">
          <%#= link_to image_tag(product.image.url(:thumb)), product %>
        </div>
        <div>
          <ul>
            <li><strong>UPC:</strong> <%= product.upc %></li>
            <li><strong>Price: <%= number_to_currency(product.price, :precision => 2) %></strong></li>
          </ul>
        </div>
      </td>
    <% end %>
  </tr>
</table>

<div style="text-align:center; margin-top:20px;">
  <%= will_paginate @products %>
</div>

app/views/products/search.html.erb
<h1>Search</h1>

<p>You searched for: <strong><%= raw @q %></strong></p>

<div style="text-align:right;">
  order by: <% %w(name upc price).each do |sort| %>
    <%= link_to sort, {:action => 'search', :order => sort, :page => params[:page] || 1} %>
  <% end %>
</div>

<% num_cols = 5 %>
<table cellpadding="10" cellspacing="0" border="0" width="100%">
  <tr>
    <% @products.each_with_index do |product, index| %>
    <% if index%num_cols == 0 %>
    </tr><tr>
    <% end %>
      <td align="center" width="<%= 100.0/num_cols %>%">
        <h3><%= link_to product.name, product_path(session[:session_secret], product) %></h3>
        <div class="photo">
          <%#= link_to image_tag(product.image.url(:thumb)), product %>
        </div>
        <div>
          <ul>
            <li><strong>UPC:</strong> <%= product.upc %></li>
            <li><strong>Price: <%= number_to_currency(product.price, :precision => 2) %></strong></li>
          </ul>
        </div>
      </td>
    <% end %>
  </tr>
</table>

<div style="text-align:center; margin-top:20px;">
  <%= will_paginate @products %>
</div>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>

<div class="photo left">
  <%#= link_to image_tag(@product.image.url(:medium)), @product.image.url(:large), :target => '_BLANK' %>
</div>

<p><%= @product.description %></p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <%= form_tag add_to_cart_path, :method => :post do %>
    <%= hidden_field_tag :product_id, @product.id %>
    <a href="#add" onclick="javascript:$(this).parent().submit();">add to cart</a>
  <% end %>
</p>

<div class="clear"></div>

<div id="reviews">
  <h2>Reviews for <%= @product.name %></h2>
  
  <table cellpadding="10" cellspacing="0" border="0" width="100%">
    <% @product.reviews.each do |review| %>
    <tr valign="middle">
      <td width="150px" align="center"><%= review.user.nil? ? 'Anonymous' : link_to(review.user.name, review.user) %></td>
      <td><%= raw(review.review) %></td>
    </tr>
    <% end %>
  </table>
  
  <%= form_for [@product, @product.reviews.build], :url => product_reviews_path(session[:session_secret], @product) do |f| %>
    <%= f.text_area :review %>
    <%= f.submit 'post my review' %>
  <% end %>
</div>