config/routes.rb
Dvra::Application.routes.draw do  
  scope ':session_secret' do
    # account functions
    resources :users
    get 'users/:id/change_password' => 'users#change_password', :as => 'change_password'
    get 'register' => 'users#new', :as => 'register'

    # products functions
    get 'categories/:category_id(/order/:order(/page/:page))' => 'products#index', :as => 'products'
    get 'products/search(/order/:order(/page/:page))' => 'products#search', :as => 'product_search'
    get 'products/:id' => 'products#show', :as => 'product'
    post 'products/:product_id/reviews' => 'reviews#create', :as => 'product_reviews'

    # cart functions
    get 'cart' => 'cart#show', :as => 'cart'
    post 'cart/add' => 'cart#add', :as => 'add_to_cart'
    post 'cart/remove' => 'cart#remove', :as => 'remove_from_cart'
    put 'cart/update/:product_id' => 'cart#update', :as => 'update_cart_item'
  
    # mailing list functions
    post 'mailing-list' => 'mailing_list#join', :as => 'join_mailing_list'
  
    # login/logout functions
    get 'login' => 'sessions#new', :as => 'login'
    post 'login' => 'sessions#create', :as => 'login'
    delete 'logout' => 'sessions#destroy', :as => 'logout'
  
    # database stuff
    post 'change_level' => 'sessions#change_level', :as => 'change_level'
    delete 'reset' => 'sessions#reset_database', :as => 'reset_database'
  
    # static paths
    match 'statics' => 'statics#show', :as => 'statics'
  
    root :to => 'store#index', :as => 'store'
  end
  
  root :to => 'store#index', :as => 'store'
end

app/views/layouts/_flash.html.erb
<% flash.each do |fk,fv| %>
  <div class="flash" id="<%= fk %>">
    <% if fv.is_a?(Array) %>
      <ul>
        <% fv.each do |v| %>
          <li><%= raw v %></li>
        <% end %>
      </ul>
    <% else %>
      <%= raw fv %>
    <% end %>
  </div>
<% end unless flash.nil? || flash.empty? || flash.blank? %>

app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="left">
	  <%= form_tag join_mailing_list_path do %>
  		<%= text_field_tag :email %>
  		<%= submit_tag :go %>
		<% end %>
	</div>
	
	<ul class="right">
		<% %w(about\ us customer\ service contact\ us sitemap).each do |link| %>
			<li><%= link_to link, statics_path(:page => link.parameterize.gsub(/-/, '_')) %></li>
		<% end %>
	</ul>
	
	<%= image_tag 'rails.png' %>
</div>

app/views/layouts/_header.html.erb
<div id="header">
	
  <h1 class="left">
    <%= link_to store_path do %>
      The<span>Chess</span>Store
    <% end %>
  </h1>
	
	<div class="right">
		<%= form_tag product_search_path, :method => :get do %>
			<%= text_field_tag 'q' %>
			<%= submit_tag :go %>
		<% end %>
	</div>
	
	<div class="clear"></div>
	
	<ul class="right">	
  	<% if logged_in? %>
  	  <% if current_user.is_admin? %>
  	    <li><%= link_to 'admin', users_path %></li>
  	  <% end %>
  		<li><%= link_to 'my account', user_path(session[:session_secret], current_user) %></li>
  		<li><%= link_to 'logout', logout_path, :method => :delete %></li>
  	<% else %>
  		<li><%= link_to 'login', login_path %></li>
  		<li><%= link_to 'register', new_user_path %></li>
  	<% end %>
  	<li><%= link_to "cart (#{session[:cart].nil? ? 0 : session[:cart][:items].size})", cart_path %></li>
	</ul>
	
	<div class="clear" style="height: 10px;"></div>
</div>

app/views/layouts/_info_bar.html.erb
<div id="difficulty">
  <div style="float:left; padding-left: 10px;">
    Sandboxed at <%= link_to truncate(request.fullpath[1..-1], :length => 125), request.url %>
  </div>
  <div style="float: right; padding-right: 10px;">
    <%= form_tag change_level_path do %>
      <label>security:</label> <%= select_tag "level", options_for_select([['low (easy)', 1], ['medium (moderate)', 2], ['high (difficult)', 3]], session[:level].to_s) %>
      <%= submit_tag 'change' %>
      &nbsp;|&nbsp;
      <%= link_to 'reset database', reset_database_path, :method => :delete, :confirm => "Are you sure you want to reset the database? In addition to restoring the database to its original state, this will also clear any session information.\n\nThis process can take up to 10 seconds, so please be patient." %>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<ul id="navigation">
	<% Category.where(:session_id => session[:session_id]).sorted.each do |link| %>
		<li><%= link_to link.name.html_safe, products_path(session[:session_secret], link) %></li>
	<% end %>
</ul>

<div class="clear"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Chess Store - A Damn Vulnerable Rails App</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
	<!-- Guys, I set up a default 'admin' account automatically for us to use in testing and the like.  -->
</head>
<body>
	
	<%= render :partial => 'layouts/info_bar' %>
	
	<div id="wrapper">
		
		<div id="content">
			<%= render :partial => 'layouts/header' %>
			<%= render :partial => 'layouts/navigation' %>
			<%= breadcrumbs(nil) %>
			<%= render :partial => 'layouts/flash', :locals => { :flash => flash } %>
			
			<%= yield %>
			
			<div class="clear"></div>
		</div>
		
		<%= render :partial => 'layouts/footer' %>
	</div>

</body>
</html>